### ISSUE TITLE
Question Code

### ISSUE THREAD

**Issue by hannespreishuber** [KristofferStrube/Blazor1brc#1]
why you are using 
   ref CitySummary citySummary = ref CollectionsMarshal.GetValueRefOrAddDefault(cities, workingNameHash, out bool exists);

and not something like 
if (cities.ContainsKey(workingNameHash))
{

**Comment by KristofferStrube** [comment]
The first thing to note is that `CollectionsMarshal.GetValueRefOrAddDefault` returns a reference to the `CitySummary` struct, whereas `ContainsKey` only returns a boolean indicating whether the hash exists among the dictionary keys.

Apart from this, I assume you would then get the value associated with the key if the key existed. The problem with this is that structs are copied-by-value instead of copied-by-ref like classes are. This would mean that you would need to get a copy of the struct, then edit that copy, and then overwrite the existing struct in the dictionary which is a lot of allocation and unnecessary instructions. By using `CollectionsMarshal.GetValueRefOrAddDefault` we instead get the struct by reference, which means we can edit the struct directly instead of having to update the dictionary again.

Hope that clears things up. If you are still unsure about how this works then I recommend that you read the documentation on [Structs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct) and then take a look at the [CollectionMarshall](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal?view=net-8.0) class.

**Comment by hannespreishuber** [comment]
thanks sounds reasonable 
I worked with your code and replaced it with Contains- and its faster. But just a 800k dataset 
My itention is to look at the new AOT compilation and the new unsave way  JSImport to access JS functions/data, instead of IJSRuntime

**Comment by KristofferStrube** [comment]
I don't see how using Contains alone could make it faster. What other methods do you use to read from and insert into the dictionary?

Apart from this my project already uses AOT and there is no performance benefit from using JSImport instead of IJSRuntime as they are simply two APIs for making the same invocations. Just wanted to note this if you were hoping for this to be the case.
